flowchart TD
    Head[(COLLECTION\nOF\nSKILLS)]---ska[(Skill A)]
    Head---skb[Skill B]
    Head---skc[(Skill C)]

    ska---fun1[Function A-1]
    ska---fun2[Function A-2]

    skb---fun3[Function B-1]

    skc---fun4[Function C-1]
    skc---fun5[Function C-2]
    skc---fun6[Function C-3]
    skc---fun7[Function C-4]